---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# image:
#   file: .gitpod.Dockerfile
image: gitpod/workspace-full
tasks:
  - init: >
      cmake -S. -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON &&
      cmake --build build --target all 

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - llvm-vs-code-extensions.vscode-clangd
    - ms-vscode.cmake-tools
    - vadimcn.vscode-lldb
